services:
  backend-amsterdam-app:
    build: ./backend
    container_name: backend_c
    ports:
      - "6060:6060"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: ["nodemon", "app.js"]
  frontend-amsterdam-app:
    build: ./frontend
    container_name: frontend_c
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true